apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fhc-web
data:
    nginx.conf: |
      # 启动多worker进程
      worker_processes  auto;
      events {
        worker_connections  1024;
      }
      http {
        include    /etc/nginx/mime.types;

        # 设置缓存信息
        proxy_temp_path /tmp/temp_dir;
        proxy_cache_path /tmp/cache levels=1:2 keys_zone=cache_one:100m inactive=1d max_size=1g;

        # 配置springboot服务集群
        #upstream seeker_server {
        #  server service-xxxxx-gateway-fat:7000 weight=3;
        #  keepalive 32;
        #}

        default_type  application/octet-stream;
        # 日志格式
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"'
                          '"$upstream_cache_status"';
        sendfile        on;
        keepalive_timeout  65;
        # 启用gzip压缩
        gzip  on;

        server {
            listen 80;
            # listen 443;
            # ssl on;
            # ssl_certificate /etc/nginx/ssl/server.crt;
            # ssl_certificate_key /etc/nginx/ssl/server.key;

            server_name  localhost;

            # 这是新版本的Nginx转发
            # return 301 https://$server_name$request_uri;

            charset utf-8;
            # 日志输出
            # access_log  /var/log/nginx/host.access.log  main;

            # nginx静态文件缓存
            location ~* ^.+\.(gif|jpg|jpeg|png|htm|html|css|js|flv|ico|swf|cur|gz|svg|map|mp4|ogg|ogv|webm)$ {
                proxy_redirect off;
                # 关闭静态资源的访问日志
                access_log off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_cache cache_one;
                proxy_cache_key   $host$uri$is_args$args;
                proxy_cache_valid 200 302 1h;
                proxy_cache_valid 301 1d;
                proxy_cache_valid any 1m;
                expires 7d;
                add_header Nginx-Cache "$upstream_cache_status";
                add_header X-Frame-Options sameorigin always;
            }

            # vuejs静态文件配置
            location / {
              
              root   /etc/nginx/html;
              try_files $uri $uri/ @router;
              index  index.html index.htm;
             
            }
            # 对应上面的@router，主要原因是路由的路径资源并不是一个真实的路径，所以无法找到具体的文件
            # 因此需要rewrite到index.html中，然后交给路由在处理请求资源
            location @router {
              rewrite ^.*$ /index.html last;
            }

            # 反向代理springboot接口服务
            #location /xxxxx/api/ {
            #  # 解决springboot中获取远程ip的问题
            #  proxy_set_header Host $host;
            #  proxy_set_header X-Real-IP $remote_addr;
            #  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #  proxy_pass http://seeker_server/gateway/xxxx/api/;
            #  proxy_http_version 1.1;
            #  proxy_set_header Connection "";
            #}

            error_page  404              /404.html;

          # redirect server error pages to the static page /500.html
          #
            error_page   500 502 503 504  /500.html;
              location = /50x.html {
              root   /etc/nginx/html;
            }
        }
      }
