apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhc-web
  labels:
    app: fhc-web
spec:
  selector:
    matchLabels:
      app: fhc-web
  replicas: ${replicas}
  template:
    metadata:
      labels:
        app: fhc-web
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: qcloudregistrykey
      containers:
      - name: fhc-web
        image: ${image}
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 0.1
            memory: 1024Mi
          limits:
            cpu: 0.5
            memory: 2048Mi
---
kind: Service
apiVersion: v1
metadata:
  name: fhc-web
  labels:
    app: fhc-web
spec:
  type: NodePort
  selector:
    app: fhc-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000